#!/bin/bash
# Characters on the ORIGINAL UCI file (paper_data/characters_uci, numbering = the
# authors'), on the authors' own instance files, each instance measured ONCE
# (as in src/fut_paper_experiments.cpp):
#
#   LMF      queries/characters_uci_lmf_pairs.txt  = the 210 files
#            test_data/fut_val_computation_benchmark_queries/characters_full_<s1>_<s2>.txt
#            in harness order (21,000 pairs); arms original, candidate5, candidate5_noslack
#   decider  tag paperq : the authors' 23 sets x 1,000 (all / same-character), factors 2^l
#            tag paperq4: the same pairs, factors (1 +- 4^l) as in the paper text
#            (generated by `paper_bench gen`, see run_decider.sh); arms original, candidate5
#
#   bash paper_bench/run_uci.sh lmf      [CPU]     -> results/characters_uci_lmf_<arm>_r1.csv
#   bash paper_bench/run_uci.sh decider  [CPU]     -> results/characters_uci_<all|same>_<tag>_<l>_<sign>_<arm>_r1.csv
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; PB="$ROOT/paper_bench"
WHAT="${1:-lmf}"; CPU="${2:-2}"
DIR="$ROOT/paper_data/characters_uci/data"
ORIG="$HOME/b_pb_original/paper_bench"; C5="$HOME/b_pb_candidate5/paper_bench"
LS_PLUS="-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2"; LS_MINUS="-10 -9 -8 -7 -6 -5 -4 -3 -2 -1"
mkdir -p "$PB/results"
run() { local arm=$1; shift; t0=$EPOCHREALTIME; "$@" 2>/dev/null; echo "[uci] $arm done in $(awk -v a="$t0" -v b="$EPOCHREALTIME" 'BEGIN{printf "%.0f", b-a}') s" >&2; }

if [ "$WHAT" = lmf ]; then
  P="$PB/queries/characters_uci_lmf_pairs.txt"
  run "lmf original"   taskset -c "$CPU" "$ORIG" lmf "$P" "$DIR" "$PB/results/characters_uci_lmf_original_r1.csv"
  run "lmf candidate5" taskset -c "$CPU" "$C5"   lmf "$P" "$DIR" "$PB/results/characters_uci_lmf_candidate5_r1.csv"
  run "lmf candidate5_noslack" env MAXREGION=cech MAXREGION_SLACK=0 taskset -c "$CPU" "$C5" lmf "$P" "$DIR" "$PB/results/characters_uci_lmf_candidate5_noslack_r1.csv"
elif [ "$WHAT" = decider ]; then
  for tag in paperq paperq4; do for ds in all same; do
    qp="$PB/queries/characters_uci_${ds}_${tag}"
    if [ ! -f "${qp}_computed_distances.check" ]; then
      echo "[uci] generating $tag ($ds) with original ..." >&2
      taskset -c "$CPU" "$ORIG" gen "$PB/queries/characters_uci_${ds}_pairs.txt" "$DIR" "$qp" 2>&1 | tail -1 >&2
    fi
    for arm in original candidate5; do
      bin="$ORIG"; [ "$arm" = candidate5 ] && bin="$C5"
      t0=$EPOCHREALTIME
      for l in $LS_PLUS;  do taskset -c "$CPU" "$bin" decider "${qp}_${l}_plus.txt"  "$DIR" "$PB/results/characters_uci_${ds}_${tag}_${l}_plus_${arm}_r1.csv"  2>/dev/null; done
      for l in $LS_MINUS; do taskset -c "$CPU" "$bin" decider "${qp}_${l}_minus.txt" "$DIR" "$PB/results/characters_uci_${ds}_${tag}_${l}_minus_${arm}_r1.csv" 2>/dev/null; done
      echo "[uci] decider $tag $ds $arm done in $(awk -v a="$t0" -v b="$EPOCHREALTIME" 'BEGIN{printf "%.0f", b-a}') s" >&2
    done
  done; done
fi
echo "[uci] $WHAT all done" >&2
