#!/bin/bash
# Sigspatial: the FULL 20,199-curve GIS Cup set (paper_data/sigspatial, headers stripped as
# the authors' fetch_and_convert_data.py does) on the authors' own decider instances
# (test_data/fut_decider_benchmark_queries/sigspatial_fut_decider_*), each instance measured
# ONCE, exactly as run_uci.sh does for Characters.
#
#   decider  tag paperq : the authors' 23 sets x 1,000 pairs, factors 2^l (their files, copied
#                         to queries/sigspatial_paperq_*)
#            tag paperq4: the same 1,000 pairs, factors (1 +- 4^l) as in the paper text,
#                         generated by `paper_bench gen` (delta* recomputed by original)
#            arms original, candidate5 (exact predicates, no slack)
#   lmf      value computation on the same 1,000 pairs; arms original, candidate5_noslack,
#            candidate5_exact  (the paper's Table 4 has no Sigspatial row; this is ours)
#
#   bash paper_bench/run_sig.sh decider [CPU] -> results/sigspatial_<tag>_<l>_<sign>_<arm>_r1.csv
#   bash paper_bench/run_sig.sh lmf     [CPU] -> results/sigspatial_lmf_<arm>_r1.csv
set -u
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; PB="$ROOT/paper_bench"
WHAT="${1:-decider}"; CPU="${2:-2}"
DIR="$ROOT/paper_data/sigspatial/data"
ORIG="${ORIG:-$HOME/b_pb_original/paper_bench}"; C5="${C5:-$HOME/b_pb_candidate5/paper_bench}"
LS_PLUS="-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 0 1 2"; LS_MINUS="-10 -9 -8 -7 -6 -5 -4 -3 -2 -1"
P="$PB/queries/sigspatial_pairs.txt"
mkdir -p "$PB/results"
secs() { awk -v a="$1" -v b="$EPOCHREALTIME" 'BEGIN{printf "%.0f", b-a}'; }

if [ "$WHAT" = lmf ]; then
  t0=$EPOCHREALTIME; taskset -c "$CPU" "$ORIG" lmf "$P" "$DIR" "$PB/results/sigspatial_lmf_original_r1.csv" 2>/dev/null
  echo "[sig] lmf original done in $(secs $t0) s" >&2
  t0=$EPOCHREALTIME; env MAXREGION=cech MAXREGION_SLACK=0 taskset -c "$CPU" "$C5" lmf "$P" "$DIR" "$PB/results/sigspatial_lmf_candidate5_noslack_r1.csv" 2>/dev/null
  echo "[sig] lmf candidate5_noslack done in $(secs $t0) s" >&2
  t0=$EPOCHREALTIME; env MAXREGION=cech MAXREGION_SLACK=0 MAXREGION_EXACT=1 taskset -c "$CPU" "$C5" lmf "$P" "$DIR" "$PB/results/sigspatial_lmf_candidate5_exact_r1.csv" 2>/dev/null
  echo "[sig] lmf candidate5_exact done in $(secs $t0) s" >&2
elif [ "$WHAT" = decider ]; then
  for tag in paperq paperq4; do
    qp="$PB/queries/sigspatial_${tag}"
    if [ ! -f "${qp}_computed_distances.check" ]; then
      echo "[sig] generating $tag with original ..." >&2
      t0=$EPOCHREALTIME; taskset -c "$CPU" "$ORIG" gen "$P" "$DIR" "$qp" 2>&1 | tail -1 >&2
      echo "[sig] gen $tag done in $(secs $t0) s" >&2
    fi
    for arm in original candidate5; do
      bin="$ORIG"; envs=""
      if [ "$arm" = candidate5 ]; then bin="$C5"; envs="MAXREGION=cech MAXREGION_SLACK=0 MAXREGION_EXACT=1"; fi
      t0=$EPOCHREALTIME
      for l in $LS_PLUS;  do env $envs taskset -c "$CPU" "$bin" decider "${qp}_${l}_plus.txt"  "$DIR" "$PB/results/sigspatial_${tag}_${l}_plus_${arm}_r1.csv"  2>/dev/null; done
      for l in $LS_MINUS; do env $envs taskset -c "$CPU" "$bin" decider "${qp}_${l}_minus.txt" "$DIR" "$PB/results/sigspatial_${tag}_${l}_minus_${arm}_r1.csv" 2>/dev/null; done
      echo "[sig] decider $tag $arm done in $(secs $t0) s" >&2
    done
  done
fi
echo "[sig] $WHAT all done" >&2
